// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzey9czMjY2PcdmUMfTG0tkDP-m6rerzo',
    appId: '1:518930904090:web:9092c2ae2691b05e28cda3',
    messagingSenderId: '518930904090',
    projectId: 'shared-mtsbz',
    authDomain: 'shared-mtsbz.firebaseapp.com',
    storageBucket: 'shared-mtsbz.appspot.com',
    measurementId: 'G-ELT23Z9KC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_yIbr7A5gbXYCyBweRFSxDfJKOPrdreM',
    appId: '1:518930904090:android:8bb5878295d426eb28cda3',
    messagingSenderId: '518930904090',
    projectId: 'shared-mtsbz',
    storageBucket: 'shared-mtsbz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiWiHr89xHTlVmI6nMIQ44hk5mIoWB4UQ',
    appId: '1:518930904090:ios:2a09d68cd098a60928cda3',
    messagingSenderId: '518930904090',
    projectId: 'shared-mtsbz',
    storageBucket: 'shared-mtsbz.appspot.com',
    iosBundleId: 'com.matiasbaez.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiWiHr89xHTlVmI6nMIQ44hk5mIoWB4UQ',
    appId: '1:518930904090:ios:fcfa77c91265412128cda3',
    messagingSenderId: '518930904090',
    projectId: 'shared-mtsbz',
    storageBucket: 'shared-mtsbz.appspot.com',
    iosBundleId: 'com.matiasbaez.pushNotification.RunnerTests',
  );
}
